<<<<<<< HEAD
app:
  minDelaySeconds: 3
  maxDelaySeconds: 10
  topic:
    topicName: pingpong
kafka:
  bootstrapServers: localhost:9092
  kafkaAppId: ping-pong
  autoOffsetReset: latest
=======
server:
  port: 3015
app:
  kafkaApplicationIdConfig: pingpongpatfourplayer-app-id
  kafkaApplicationName: pingpongpatfourplayer
  topicName: pingpongpatfourplayer
  minDelaySeconds: 3
  maxDelaySeconds: 10
kafka:
  kafkaAppId: pingPong
  autoOffsetReset: latest
  bootstrapServers: localhost:9092
  schemaRegistryUrl: http://registry.amq-streams.apps.openshift.cedruscloud.com #http://localhost:10000
  useMockAvroSchemaRegistryClient: true
  stateStoreDirectoryPath:
  useCustomerStateStoreDirectory: false
  autoOffsetResetConfig: earliest
  securityEnabled: false
  apiKey:
  securityProtocol:
  sslProtocolConfig:
  psslTruststorePasswordConfig:
  sslTruststoreLocationConfig:
  saslMechanism:
  saslJaasUserName:
  enableSslEndpointAuthentication:
datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
>>>>>>> b5d784298fa0736c5821cf4e4f4328cbf8b371fe
logging.level.com.cedrus: DEBUG