server:
  port: 3015
app:
  kafkaApplicationIdConfig: pingpongfourplayer-app-id
  kafkaApplicationName: pingpongfourplayer
  topicName: pingpongfourplayer
  minDelaySeconds: 3
  maxDelaySeconds: 10
kafka:
  kafkaAppId: pingPong
  autoOffsetReset: latest
  bootstrapServers: localhost:9092
  schemaRegistryUrl: http://localhost:10000 #http://registry.amq-streams.apps.openshift.cedruscloud.com
  useMockAvroSchemaRegistryClient: false
  stateStoreDirectoryPath:
  useCustomerStateStoreDirectory: false
  autoOffsetResetConfig: earliest
  securityEnabled: false
  apiKey:
  securityProtocol:
  sslProtocolConfig:
  psslTruststorePasswordConfig:
  sslTruststoreLocationConfig:
  saslMechanism:
  saslJaasUserName:
  enableSslEndpointAuthentication:
spring:
  datasource:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres
      username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
logging.level.com.cedrus: DEBUG