app:
  minDelaySeconds: 3
  maxDelaySeconds: 10
  topic:
    topicName: pingpongpat
kafka:
  bootstrapServers: localhost:9092
  kafkaAppId: ping-pong
  autoOffsetReset: latest
datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
logging.level.com.cedrus: DEBUG