/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package com.cedrus.patpetillo.springkafkapingpong.avro;

@SuppressWarnings("all")
/** Represents the possible color of a Ping Pong ball */
@org.apache.avro.specific.AvroGenerated
public enum ColorType {
  BLACK,
  RED,
  BLUE,
  PURPLE,
  ORANGE;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"enum\",\"name\":\"ColorType\",\"namespace\":\"com.cedrus.patpetillo.springkafkapingpong.avro\",\"doc\":\"Represents the possible color of a Ping Pong ball\",\"symbols\":[\"BLACK\",\"RED\",\"BLUE\",\"PURPLE\",\"ORANGE\"]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }
}
