/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package com.cedrus.patpetillo.springkafkapingpong.avro;

@SuppressWarnings("all")
/** Represents who is serving the Ping Pong ball */
@org.apache.avro.specific.AvroGenerated
public enum ServerType {
  PLAYER_ONE_SERVICE,
  PLAYER_TWO_SERVICE,
  PLAYER_THREE_SERVICE,
  PLAYER_FOUR_SERVICE;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"enum\",\"name\":\"ServerType\",\"namespace\":\"com.cedrus.patpetillo.springkafkapingpong.avro\",\"doc\":\"Represents who is serving the Ping Pong ball\",\"symbols\":[\"PLAYER_ONE_SERVICE\",\"PLAYER_TWO_SERVICE\",\"PLAYER_THREE_SERVICE\",\"PLAYER_FOUR_SERVICE\"]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }
}
